# Generated by Django 5.0.7 on 2025-01-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_freeuserprofile_delete_free_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeuserprofile',
            name='subscription_status',
            field=models.CharField(default='Free User', max_length=50),
        ),
    ]
