# Generated by Django 5.0.7 on 2025-01-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0004_freeuserprofile_subscription_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freeuserprofile',
            name='current_plan',
        ),
        migrations.RemoveField(
            model_name='freeuserprofile',
            name='has_logged_in_before',
        ),
        migrations.AddField(
            model_name='freeuserprofile',
            name='trial_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='freeuserprofile',
            name='subscription_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
