# Generated by Django 5.0.7 on 2025-01-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0005_remove_freeuserprofile_current_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeuserprofile',
            name='current_plan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='freeuserprofile',
            name='subscription_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
