# Generated by Django 5.0.7 on 2025-01-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0007_alter_freeuserprofile_current_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeuserprofile',
            name='current_plan',
            field=models.CharField(default='No Plan', max_length=50),
        ),
    ]
